# Generated by Django 5.2.1 on 2025-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(choices=[('maiz', 'Maíz'), ('trigo', 'Trigo'), ('arroz', 'Arroz'), ('cafe', 'Café'), ('soya', 'Soya'), ('cebada', 'Cebada'), ('avena', 'Avena'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('cantidad_cosechada', models.DecimalField(decimal_places=2, help_text='Cantidad en kilogramos', max_digits=10)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('fecha_recoleccion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
                'ordering': ['-fecha_recoleccion'],
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
